### PR TITLE
Simple documentation fixes for indexing specifics

### PR DESCRIPTION
**Pull request by Purg**
Basic fixup of originally ported documentation files to be package-specific.

### CODE REVIEW

**Comment by Purg** [comment]
I might take a quick peek at [sphinx.ext.intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping) but otherwise @bardkw PTAL

**Comment by Purg** [comment]
I won't be adding anything regarding intersphinx at this time.

**Comment by Purg** [comment]
Force rebased with no change to observe triggering of RTD build check, which I see.

**Comment by bardkw** [comment]
LGTM

**Pull request merged**
